Maven Integration
JACornelius/TwitterApp pull request #1
Opened 2018-06-26 21:09 UTC by JACornelius

2018-06-26 21:21 UTC, kev-chan commented
add to gitignore
 .class
 twitter4j.properties
add instructions for how to generate a twitter4j properties file if one doesn't exist however

2018-06-26 21:23 UTC, kev-chan commented
remove any unneeded checked in jar files and class files as well

2018-06-26 21:23 UTC, kev-chan commented
remove target directory from checked in code and add to gitignore as well

2018-06-26 21:24 UTC, kev-chan commented
please make the version of your app 1.0-SNAPSHOT

2018-06-26 21:25 UTC, kev-chan commented
your groupId/artifactId should match your package/app name
also move the groupId/artifactId/version info to the top of the xml

2018-06-26 21:26 UTC, kev-chan commented
put the twitter4j version inside a property in the pom file as well

2018-06-27 04:28 UTC, kev-chan commented
remove the checked in files from the target directory.  You may need to explicitly 'git add' them to make sure they get pushed to the remote branch.

2018-06-27 04:29 UTC, kev-chan requested changes
you probably need to update your pom.xml file since you rename a class

2018-06-27 04:29 UTC, kev-chan commented on .gitignore
> +/src/main/java/twitterapp/src/Main.class
you can use *.class

2018-06-27 04:29 UTC, kev-chan commented on src/main/java/twitter4j.properties
> +oauth.accessToken =
you may want to consider deleting the old keys and generating new ones so your keys don't make it out publicly

2018-06-27 04:29 UTC, kev-chan commented on target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
> +twitterapp/src/Timeline.class
remove this and all of the other '.lst files"

2018-06-27 04:29 UTC, kev-chan commented on target/maven-archiver/pom.properties
> +#Created by Apache Maven 3.5.4
this should not be checked in either

2018-06-27 15:03 UTC, JACornelius commented
okay I think I completed all these changes you mentioned

2018-06-27 18:48 UTC, merged